services:
  - name: warzone-gun-search-bot
    type: web
    build:
      type: dockerfile
      dockerfile: |
        FROM python:3.11-slim
        
        # Install system dependencies
        RUN apt-get update && apt-get install -y \
            jq \
            curl \
            unzip \
            && rm -rf /var/lib/apt/lists/*
            
        # Set working directory
        WORKDIR /app
        
        # Copy requirements first for better caching
        COPY discord_bot_requirements.txt .
        RUN pip install --no-cache-dir -r discord_bot_requirements.txt
        
        # Copy application code
        COPY . .
        
        # Download latest gun database artifact
        RUN curl -L -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$GITHUB_REPO_OWNER/$GITHUB_REPO_NAME/actions/artifacts" | \
            jq -r '.artifacts[] | select(.name=="gun-database") | .archive_download_url' | \
            xargs -I {} curl -L -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" {} -o gun-database.zip && \
            unzip gun-database.zip && \
            mv artifacts/all_guns_database.json . && \
            rm -rf artifacts gun-database.zip
        
        # Expose port
        EXPOSE 10000
        
        # Start the application
        CMD ["python", "start.py"]
    
    environment:
      - name: DISCORD_SEARCH_BOT_TOKEN
        value: ${DISCORD_SEARCH_BOT_TOKEN}
      - name: GITHUB_TOKEN
        value: ${GITHUB_TOKEN}
      - name: GITHUB_REPO_OWNER
        value: ${GITHUB_REPO_OWNER}
      - name: GITHUB_REPO_NAME
        value: ${GITHUB_REPO_NAME}
      - name: PORT
        value: "10000"
    
    ports:
      - "10000:10000"
    
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3 