services:
  - name: warzone-gun-search-bot
    type: web
    build:
      type: dockerfile
      dockerfile: Dockerfile
      buildArgs:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_REPO_OWNER: InterestingSoup
        GITHUB_REPO_NAME: warzone-gun-search-bot

    environment:
      - name: DISCORD_SEARCH_BOT_TOKEN
        value: ${DISCORD_SEARCH_BOT_TOKEN}
      - name: PORT
        value: "10000"

    ports:
      - "10000:10000"

    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3